### ISSUE TITLE
Carpeta de imagenes

### ISSUE THREAD

**Issue by confort-gabytho** [andrewsebek/Sebekdots#1]
Hola! ¿La carpeta debería quedar así? ¿La palabra imágenes va con la tilde?
/Imágenes/Wallpapers/Set
Abrazo desde Argentina.

**Comment by denoobaprolinux** [comment]
¡Oye, no me había dado cuenta de este mensaje!

Sí, debe quedar con la tilde.

**Comment by confort-gabytho** [comment]
Gracias por responderme.
Lo gracioso es que yo no me había dado cuenta de tu respuesta, jajaja!
